name: freelance_kg
description: "Freelance KG - биржа фриланса Кыргызстана"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.7.0
  go_router: ^14.8.1
  json_annotation: ^4.9.0
  flutter_secure_storage: ^9.2.4
  stomp_dart_client: ^2.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  shimmer: ^3.0.0
  google_sign_in: ^6.2.2
  firebase_core: ^3.8.1
  firebase_messaging: ^15.2.1
  flutter_local_notifications: ^18.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.4
  build_runner: ^2.4.15

flutter:
  uses-material-design: true

  assets:
    - assets/
